services:
  claude-code-log:
    build: .
    container_name: claude-code-log
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: tail -f /dev/null
    stdin_open: true
    tty: true