services:
  claude-code-log:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: claude-code-log
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: ["bash"]
    stdin_open: true
    tty: true
    environment:
      - TERM=xterm-256color
    init: true
