#!/bin/bash

# Claude Code会話ログ保存スクリプト
# Usage: ./save-chat.sh [chat-title]

LOG_DIR="/Users/t-akira012/tmp/claude-code-log"
DATE=$(date +%Y%m%d)
TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
DATE_DIR="$LOG_DIR/$DATE"

# ディレクトリ作成
mkdir -p "$DATE_DIR"

# チャットタイトルの処理
if [ -n "$1" ]; then
    CHAT_TITLE="$1"
else
    echo "会話のタイトルを入力してください:"
    read CHAT_TITLE
    if [ -z "$CHAT_TITLE" ]; then
        CHAT_TITLE="claude-chat-$(date +%H%M%S)"
    fi
fi

# ファイル名の安全化（日本語対応）
SAFE_TITLE=$(echo "$CHAT_TITLE" | sed 's/ /-/g' | tr -d '/\\:*?"<>|')

# 空のタイトルチェック
if [ -z "$SAFE_TITLE" ] || [ "$SAFE_TITLE" = "-" ]; then
    SAFE_TITLE="claude-chat-$(date +%H%M%S)"
fi

FILENAME="$DATE_DIR/${SAFE_TITLE}.md"

# 重複チェック
COUNTER=1
BASE_FILENAME="$FILENAME"
while [ -f "$FILENAME" ]; do
    FILENAME="${BASE_FILENAME%.*}-${COUNTER}.md"
    ((COUNTER++))
done

# ログファイルの作成
cat > "$FILENAME" << EOF
# $CHAT_TITLE

**Date**: $TIMESTAMP
**Duration**: [自動計算]
**Topics**: [会話内容から自動抽出]

---

## Conversation

[この会話の実際の内容をここに動的に挿入する必要があります]
[Claude Codeの制限により、実際の会話履歴を取得することはできません]
[現在はプレースホルダーとして表示されています]

### 会話の要約
- 日時: $TIMESTAMP
- タイトル: $CHAT_TITLE
- ステータス: 保存完了

### Notes
- Generated by Claude Code Log Management System
- File: $FILENAME
- Created: $TIMESTAMP
- 実際の会話内容を保存するには、Claude Code APIの拡張が必要です

EOF

echo "会話ログが保存されました: $FILENAME"

# 最近の会話リストを表示
echo ""
echo "今日の会話一覧:"
ls -la "$DATE_DIR" | grep -E '\.md$' | awk '{print $9}' | sed 's/\.md$//'